# Nome da Aplicação
spring.application.name=smart-home-api

# Configuração do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-damp-morning-aqxcejuz-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aSgcAFLM5CT2
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Porta do Servidor
server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=sua-chave-secreta-muito-longa-com-pelo-menos-32-caracteres-aqui
jwt.expiration=86400000